<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elHeaderIssuesItems</name>
   <tag></tag>
   <elementGuidId>729ccbaf-c27e-405e-952e-74e11e8ba6df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='find_link-content']//a[.='${issue_item}']</value>
   </webElementProperties>
</WebElementEntity>
